-- MySQL Script generated by MySQL Workbench
-- Wed Apr 21 10:54:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_RH
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_RH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_RH` DEFAULT CHARACTER SET utf8 ;
USE `db_RH` ;

-- -----------------------------------------------------
-- Table `db_RH`.`tb_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_RH`.`tb_empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nome_empresa` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_empresa`),
  UNIQUE INDEX `id_empresa_UNIQUE` (`id_empresa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_RH`.`registro_funcionaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_RH`.`registro_funcionaries` (
  `id_funcionarie` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `idade` INT NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `salario` DECIMAL(8,2) NOT NULL,
  `fk_empresa` INT NOT NULL,
  PRIMARY KEY (`id_funcionarie`, `fk_empresa`),
  UNIQUE INDEX `id_funcionarie_UNIQUE` (`id_funcionarie` ASC) VISIBLE,
  INDEX `fk_registro_funcionaries_tb_empresa_idx` (`fk_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_registro_funcionaries_tb_empresa`
    FOREIGN KEY (`fk_empresa`)
    REFERENCES `db_RH`.`tb_empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
